"""empty message

Revision ID: 451f01d9165d
Revises: fea11a7a6445
Create Date: 2023-03-27 15:31:19.092072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451f01d9165d'
down_revision = 'fea11a7a6445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password'))

    # ### end Alembic commands ###
