"""Add bio field in Profile module

Revision ID: b6d9ee22eb16
Revises: cc81b52012f8
Create Date: 2023-04-06 14:33:52.144913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d9ee22eb16'
down_revision = 'cc81b52012f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
